services:
    shadesoft_image.converter:
        class: ShadeSoft\GDImage\Converter
        arguments: []
        public: true
    shadesoft_image.sizer:
        class: ShadeSoft\GDImage\Sizer
        arguments: []
        public: true
    shadesoft_image.cached_sizer:
        class: ShadeSoft\GDImage\CachedSizer
        arguments: []
        public: true
    shadesoft_image.twig_filter:
        class: ShadeSoft\ImageBundle\Twig\FilterExtension
        arguments: ["@shadesoft_image.sizer"]
        public: false
        tags:
            - { name: twig.extension }
