language: php
sudo: false
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_install:
    - phpenv config-add travis.php.ini
    - composer self-update

install: composer install --dev --prefer-dist --no-suggest

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/phpunit --bootstrap vendor/autoload.php vendor/shadesoft/gd-image/tests
    - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
    - rm tests/img/test.jpg
