language: php
sudo: false
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_install:
    - composer self-update

install: composer update

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/phpunit --bootstrap vendor/autoload.php vendor/shadesoft/gd-image/tests
