language: php
sudo: false
php:
    - 5.3
    - 5.6
    - 7.0
    - 7.1
    - 7.2

matrix:
    include:
        - php: 5.3
          env: SYMFONY_VERSION='2.3.*'
        - php: 5.6
          env: SYMFONY_VERSION='2.7.*'
        - php: 5.6
          env: SYMFONY_VERSION='2.8.*'
        - php: 5.6
          env: SYMFONY_VERSION='3.0.*'
        - php: 5.6
          env: SYMFONY_VERSION='3.1.*'
        - php: 5.6
          env: SYMFONY_VERSION='3.2.*'
        - php: 7.0
          env: SYMFONY_VERSION='3.3.*'
        - php: 7.1
          env: SYMFONY_VERSION='3.4.*'
        - php: 7.2
          env: SYMFONY_VERSION='4.*'

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install: composer update $COMPOSER_FLAGS

#script: phpunit
