language: php
sudo: false
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    - phpenv config-add travis.php.ini
    - composer self-update

install: composer install --dev --prefer-dist --no-suggest

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/phpunit --bootstrap vendor/autoload.php vendor/shadesoft/gd-image/tests
    - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
